config/routes.rb
Rails.application.routes.draw do
  root to: 'users#index'

  resources :users, only: [:index, :show, :new, :create, :destroy] do
    resources :fits, only: [:new, :create]
  end
  resources :fits, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/fit.rb
class Fit < ApplicationRecord
  belongs_to :user
  belongs_to :top
  belongs_to :pant
  belongs_to :sneaker

  validates :name, presence: true
end

app/models/pant.rb
class Pant < ApplicationRecord
  has_many :fits

  validates :name, presence: true
  validates :name, uniqueness: true
end

app/models/sneaker.rb
class Sneaker < ApplicationRecord
  has_many :fits

  validates :name, presence: true
  validates :name, uniqueness: true
end

app/models/top.rb
class Top < ApplicationRecord
  has_many :fits

  validates :name, presence: true
  validates :name, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :fits, dependent: :destroy
  has_many :pants, through: :fits
  has_many :tops, through: :fits
  has_many :sneakers, through: :fits
  has_one_attached :photo

  validates :username, presence: true
  validates :username, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/fits_controller.rb
class FitsController < ApplicationController
  def new
    @user = User.find(params[:user_id])
    @fit = Fit.new
  end

  def create
    @user = User.find(params[:user_id])
    @fit = Fit.new(fit_params)
    @fit.user = @user
    if @fit.save
      redirect_to user_path(params[:user_id])
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @fit = Fit.find(params[:id])
    @fit.destroy
    redirect_to fits_path
  end

  private

  def fit_params
    params.require(:fit).permit(:name, :sneaker_id, :top_id, :pant_id, :user_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to users_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_path
  end

  private

  def user_params
    params.require(:user).permit(:username, :photo)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fits_helper.rb
module FitsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/fits/new.html.erb
<div class="container">
  <div class="new-card card mt-3">
    <div class="container form-card m-2">
      <%= simple_form_for [@user, @fit] do |f| %>
        <%= f.input :name, label:"Enter a name for your fit:" %>
        <%= f.association :top, label: "Choose a top:" %>
        <%= f.association :pant, label: "Choose a pair of pants:" %>
        <%= f.association :sneaker, label: "Choose a pair of shoes:" %>
        <%= f.submit class: 'btn btn-light m-2' %>
        <%= link_to 'Back to your fits', user_path(@user), class: 'btn btn-light m-2' %>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fitbook</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/users/index.html.erb
<body class="index">
  <div>
    <div class="index-top">
      <h1 class="main-title">Fitbook</h1>
    </div>
    <div class="index-main">
      <div class="intro-text-container">
        <div class="intro-text-box">
          <p class="intro-text">
          Put together and manage your outfits, for quick and easy reference when you're in
          need of a quick fit!
          </p>
        </div>
      </div>
      <div class="users-container">
        <%= link_to "New User", new_user_path, class:"new-button" %>
        <% @users.each do |user| %>
          <div class="user-card">
            <%= user.photo.attached? ? cl_image_tag(user.photo.key, class: "avatar") : image_tag("users/blankuser.png", class:"avatar") %>
            <div class="login-content">
              <p><%= link_to user.username, user_path(user) %></p>
            </div>
            <div class="login-actions">
              <%= link_to user_path(user), data: { turbo_method: 'delete', turbo_confirm: "Delete User: #{user.username}?" }, class: 'btn' do %>
                <i class="fa-solid fa-dumpster"></i>
              <% end %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</body>

app/views/users/new.html.erb
<div class="container">
  <div class="new-card card mt-3">
    <div class="container form-card m-2">
      <%= simple_form_for @user do |f| %>
        <%= f.input :username, label: "Enter a username"%>
        <%= f.input :photo, as: :file, label: "Upload an avatar" %>
        <%= f.submit class: 'btn btn-light m-2' %>
        <%= link_to 'Back to Main', users_path, class: 'btn btn-light m-2' %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="fit-container">
  <div class="fit-column">
    <div class="user-bar">
      <div class="user-details">
        <%= @user.photo.attached? ? cl_image_tag(@user.photo.key, class: "avatar") : image_tag("users/blankuser.png", class:"avatar") %>
        <div class="user-name">
          <h1><%= @user.username %>'s Fits</h1>
        </div>
      </div>
      <div class="user-options">
        <%= link_to "New Fit", new_user_fit_path(@user), class:"btn btn-light m-2" %>
        <%= link_to "Back to Login", users_path, class:"btn btn-light m-2" %>
      </div>
    </div>

    <div class="fit-card-container">
      <% @user.fits.each_with_index do |fit, index| %>
        <div class="fit-card">
          <h4><%= fit.name %></h4>
          <div class="item-card-container">
            <div class="item-card"><p>Top:</p><%= image_tag "tops/#{fit.top.image}.png", class:"item-img" %><p><%= fit.top.name %></p></div>
            <div class="item-card"><p>Pants:</p><%= image_tag "pants/#{fit.pant.image}.png", class:"item-img" %><p><%= fit.pant.name %></p></div>
            <div class="item-card"><p>Shoes:</p><%= image_tag "sneakers/#{fit.sneaker.image}.png", class:"item-img" %><p><%= fit.sneaker.name %></p></div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>